"""
Retrieval over the pre-built NIST SP 800-53 index (Thing 2).

Requires `python scripts/build_nist_index.py` to have been run first
(see that script's docstring for what it does and why). This module
only loads the resulting index and answers similarity queries — it
does not talk to NIST or the internet at request time, so the running
app has no runtime dependency on csrc.nist.gov being up.
"""
from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
INDEX_DIR = os.path.join(ROOT, "data", "nist_index")
sys.path.insert(0, os.path.join(ROOT, "scripts"))


@dataclass
class RetrievedControl:
    control_id: str
    label: str
    title: str
    family: str
    text: str
    score: float


class NistRetriever:
    def __init__(self, index_dir: str = INDEX_DIR):
        self.index_dir = index_dir
        meta_path = os.path.join(index_dir, "meta.json")
        if not os.path.exists(meta_path):
            raise FileNotFoundError(
                f"No NIST index found at {index_dir}. Run "
                f"`python scripts/build_nist_index.py` first."
            )
        with open(meta_path, "r", encoding="utf-8") as f:
            self.meta = json.load(f)
        with open(os.path.join(index_dir, "passages.json"), "r", encoding="utf-8") as f:
            self.passages = json.load(f)
        self.embeddings = np.load(os.path.join(index_dir, "embeddings.npy"))

        self.backend = self.meta["backend"]
        if self.backend.startswith("sentence-transformers"):
            from sentence_transformers import SentenceTransformer

            self._model = SentenceTransformer(self.backend.split("/", 1)[1])
        else:
            self._model = None  # tfidf fallback embeds queries via tfidf_fallback.embed_query_tfidf

    def _embed_query(self, query: str) -> np.ndarray:
        if self._model is not None:
            return self._model.encode([query], normalize_embeddings=True)[0]
        from tfidf_fallback import embed_query_tfidf

        return embed_query_tfidf(query, self.index_dir)

    def search(self, query: str, top_k: int = 3) -> list:
        qvec = self._embed_query(query)
        sims = self.embeddings @ qvec  # both normalized -> cosine similarity
        top_idx = np.argsort(-sims)[:top_k]
        results = []
        for i in top_idx:
            p = self.passages[i]
            results.append(
                RetrievedControl(
                    control_id=p["control_id"],
                    label=p["label"],
                    title=p["title"],
                    family=p["family"],
                    text=p["text"],
                    score=float(sims[i]),
                )
            )
        return results


def build_query_for_risk(risk) -> str:
    """Turns a ScoredRisk into a natural-language retrieval query.
    Kept simple and grounded in the risk's own fields rather than
    free-generated by an LLM, so retrieval is deterministic and
    debuggable independent of the LLM's mood that day.
    """
    bits = [risk.vulnerability_name, f"CVE {risk.cve}"]
    top_factor = max(risk.factors, key=lambda f: f.raw_score * f.weight)
    if top_factor.name == "active_threat_intel" and risk.matched_campaigns:
        bits.append("active exploitation ransomware campaign")
    if any(f.name == "internet_exposure" and f.raw_score >= 0.9 for f in risk.factors):
        bits.append("internet-facing exposed system remote access")
    comp = next((f for f in risk.factors if f.name == "compensating_controls"), None)
    if comp and comp.raw_score > 0:
        bits.append(comp.reason)
    return " ".join(bits)


if __name__ == "__main__":
    retriever = NistRetriever()
    for q in [
        "internet-exposed VPN gateway with active ransomware exploitation, no MFA",
        "unpatched software with known exploited vulnerability, flaw remediation",
        "unsupported end-of-life system component",
    ]:
        print(f"\nQuery: {q}")
        for r in retriever.search(q, top_k=3):
            print(f"  {r.label}  {r.title}  (score={r.score:.3f})")
